let state=null, page='overview', sessionToken='', frameScope=null;
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>n?new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(n/1024**3)+' GB':'—';
function when(value){if(!value)return 'Not yet';return new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
async function api(path,payload){const response=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-RepoHub-Token':sessionToken},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed');return result;}
function message(text){$('#message').textContent=text;}
async function load(){try{state=await api('/api/status');$('#backup').disabled=state.backup.running;$('#backup').textContent=state.backup.running?'Backing up…':'Back up now';$('#footer').textContent=`Status checked ${when(state.scanned_at)} · Refreshes every 30 seconds · Backups run hourly and skip unchanged repos.`;if(state.backup.running)message(`Backing up ${state.backup.current_repo||'your repos'}… You can keep using the hub.`);else if(state.backup.errors?.length)message(state.backup.errors.map(e=>(e.repo?e.repo+': ':'')+e.error).join(' · '));else message('');if(!frameScope)render();}catch(e){message('Could not reach the local helper: '+e.message);}}
function render(){if(!state)return;const rows=state.repos;$('#title').textContent=page==='overview'?'Overview':page==='backups'?'Backups':'Repo views';$('#subtitle').textContent=page==='overview'?'A clear view of your work and what’s protected.':page==='backups'?'Full copies of your repos, including uncommitted and ignored files.':'HTML views with a shared local JSON save/read service.';if(page==='views')return renderViews();const stats=page==='overview'?`<div class="stats"><div class="stat"><strong>${rows.length}</strong><span>Repos & folders</span></div><div class="stat"><strong>${rows.filter(r=>r.changed_files>0).length}</strong><span>With uncommitted work</span></div><div class="stat"><strong>${rows.filter(r=>r.last_backup).length}</strong><span>Have a verified snapshot</span></div><div class="stat"><strong>${rows.filter(r=>r.needs_backup).length}</strong><span>Changed since backup</span></div></div>`:'';$('#content').innerHTML=stats+`<section class="panel"><div class="panel-heading"><h2>${page==='overview'?'Your repos':'Latest snapshots'}</h2><small>${rows.length} workspaces</small></div><table><thead><tr><th>REPO</th><th>${page==='overview'?'LAST FILE CHANGE':'SNAPSHOT CREATED'}</th><th>${page==='overview'?'GIT STATUS':'ARCHIVE SIZE'}</th><th>BACKUP</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${escape(r.name)}<small>${escape(page==='overview'?(r.branch||'Folder without Git'):r.last_backup?.archive||r.path)}</small></td><td>${when(page==='overview'?r.last_file_change:r.last_backup?.completed_at)}${page==='overview'?`<small title="${escape(r.last_changed_file)}">${escape(r.last_changed_file||'')}</small>`:''}</td><td>${page==='overview'?(r.is_git? r.changed_files===0?'Clean':escape(r.changed_files??'?')+' changed files':'—'):bytes(r.last_backup?.archive_bytes)}</td><td><span class="badge ${r.error?'error':r.needs_backup?'pending':''}">${r.error?'Check access':r.last_backup?r.needs_backup?'Changes pending':'Snapshot current':'First backup pending'}</span></td><td><button class="link-btn workspace" data-id="${r.id}">Open workspace</button></td></tr>`).join('')}</tbody></table></section>`+`<p class="hint">${page==='backups'?'Each changed repo gets a dated, complete .tar.gz archive. Existing snapshots are kept. Archives are checksum verified on this Mac; iCloud upload is managed separately by macOS.':'“Last file change” is the newest file modification in each repo, excluding Git’s internal files. Backups include Git history, uncommitted work, and ignored files.'}</p>`+(page==='backups'?`<p class="path">${escape(state.backup_root)}</p>`:'');wireWorkspaces();}
function wireWorkspaces(){document.querySelectorAll('.workspace').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.id,null)));}
function renderViews(){const rows=state.repos;$('#content').innerHTML=`<p class="section-intro">Every repo has a small notes view to demonstrate persistent JSON. You can also register an existing HTML file from a repo. Views stay on this Mac and save data in the helper’s local workspace folder.</p><div class="view-grid">${rows.map(r=>`<article class="view-card"><h3>${escape(r.name)}</h3><p>Local workspace notes</p><button class="workspace" data-id="${r.id}">Open notes view</button>${state.views.filter(v=>v.repo_id===r.id).map(v=>` <button class="registered" data-id="${v.id}">${escape(v.title)}</button>`).join('')}</article>`).join('')}</div><section class="panel"><div class="panel-heading"><h2>Add an HTML view</h2></div><form id="view-form" class="form"><select name="repo_id">${rows.map(r=>`<option value="${r.id}">${escape(r.name)}</option>`).join('')}</select><input name="path" placeholder="Relative path, e.g. reports/dashboard.html" required><input name="title" placeholder="View name" required><button class="primary">Add view</button></form></section><p class="hint">Future views can use <code>RepoHub.getJSON('name')</code> and <code>RepoHub.saveJSON('name', value)</code>. Saves are scoped to the selected repo and check for conflicting edits.</p>`;wireWorkspaces();document.querySelectorAll('.registered').forEach(b=>b.onclick=()=>{const view=state.views.find(v=>v.id===b.dataset.id);openView(view.repo_id,view);});$('#view-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/views',Object.fromEntries(new FormData(e.target)));await load();}catch(err){message(err.message);}};}
function openView(repoId,view){const repo=state.repos.find(r=>r.id===repoId);if(!repo)return;page='views';$('#title').textContent=repo.name;$('#subtitle').textContent=view?.title||'Workspace notes · saved locally as JSON';$('#content').innerHTML='<p><button id="back">← Back to repo views</button></p><iframe id="view-frame" class="view-window" sandbox="allow-scripts allow-forms" title="Repo view"></iframe>';frameScope={repoId};const frame=$('#view-frame');frame.src=view?'/views/'+view.id+'/'+view.path.split('/').map(encodeURIComponent).join('/'):'/notes.html';$('#back').onclick=()=>{frameScope=null;render();};}
window.addEventListener('message',async event=>{const frame=$('#view-frame');if(!frameScope||!frame||event.source!==frame.contentWindow||event.origin!=='null')return;const m=event.data;if(!m||m.channel!=='repohub'||!['get','save'].includes(m.action)||typeof m.name!=='string')return;try{const path='/api/data/'+frameScope.repoId+'/'+encodeURIComponent(m.name);const result=await api(path,m.action==='save'?{value:m.value,revision:m.revision}:undefined);event.source.postMessage({channel:'repohub-result',requestId:m.requestId,result},'*');}catch(e){event.source.postMessage({channel:'repohub-result',requestId:m.requestId,error:e.message},'*');}});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{frameScope=null;page=b.dataset.page;document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('active',n===b));render();});
$('#refresh').onclick=async()=>{try{await api('/api/scan',{});await load();}catch(e){message(e.message);}};$('#backup').onclick=async()=>{try{await api('/api/backup',{});message('Backup requested.');setTimeout(load,700);}catch(e){message(e.message);}};
(async()=>{try{sessionToken=(await api('/api/session')).token;await load();setInterval(load,30000);}catch(e){message(e.message);}})();
