let state=null, page='overview', sessionToken='', frameScope=null, advanced=false;
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>n?new Intl.NumberFormat(undefined,{maximumFractionDigits:1}).format(n/1024**3)+' GB':'—';
function when(value){if(!value)return 'Not yet';return new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
async function api(path,payload){const response=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-RepoHub-Token':sessionToken},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed');return result;}
function message(text){$('#message').textContent=text;}
async function load(){try{state=await api('/api/status');$('#backup').disabled=state.backup.running;$('#backup').textContent=state.backup.running?'Backing up…':'Back up now';$('#footer').textContent=`Status checked ${when(state.scanned_at)} · Refreshes every 30 seconds · Backups run hourly and skip unchanged repos.`;if(state.backup.running)message(`Backing up ${state.backup.current_repo||'your repos'}… You can keep using the hub.`);else if(state.backup.errors?.length)message(state.backup.errors.map(e=>(e.repo?e.repo+': ':'')+e.error).join(' · '));else message('');if(!frameScope)render();}catch(e){message('Could not reach the local helper: '+e.message);}}
function backupIssue(repo){return repo.error || state.backup.errors?.find(e=>e.repo===repo.name)?.error;}
function matchLabel(repo){return backupIssue(repo)?'Backup issue':repo.needs_backup?(repo.last_backup?'Needs backup':'First backup pending'):'Matches Desktop';}
function render(){
  if(!state)return;
  $('#title').textContent=page==='views'?'Repo views':'Repos';
  $('#subtitle').textContent=page==='views'?'Your local HTML views.':'Do your iCloud backups match your Desktop repos?';
  if(page==='views')return renderViews();
  const rows=state.repos;
  const matched=rows.filter(r=>!r.needs_backup&&!backupIssue(r)).length;
  $('#content').innerHTML=`<section class="panel repo-panel"><div class="panel-heading"><h2>${matched} of ${rows.length} match</h2><label class="advanced-toggle"><input id="advanced" type="checkbox" ${advanced?'checked':''}> Advanced</label></div><ul class="repo-list">${rows.map(r=>{
    const issue=backupIssue(r), pending=r.needs_backup;
    return `<li class="repo-row"><div class="repo-line"><span class="match-icon ${issue?'error':pending?'pending':''}" aria-label="${escape(matchLabel(r))}">${issue?'!':pending?'◷':'✓'}</span><div class="repo-name">${escape(r.name)}<small>${escape(matchLabel(r))}</small></div><span class="snapshot-time">${r.last_backup?'Saved '+when(r.last_backup.completed_at):'Not backed up yet'}</span></div>${advanced?`<div class="repo-detail"><div><span>Git</span>${r.is_git?`${escape(r.branch)} · ${r.staged_files??'—'} staged · ${r.unstaged_files??'—'} unstaged · ${r.untracked_files??'—'} untracked`:'Folder without Git'}</div><div><span>Last file change</span>${when(r.last_file_change)} · ${escape(r.last_changed_file||'—')}</div>${issue?`<div class="error-text">${escape(issue)}</div>`:''}<div><span>Snapshot</span>${bytes(r.last_backup?.archive_bytes)}<p class="path">${escape(r.last_backup?.archive||'No snapshot yet')}</p></div></div>`:''}</li>`;
  }).join('')}</ul></section><p class="hint">✓ The latest backup matches the Desktop files, including uncommitted work. Copies are verified on this Mac; iCloud upload happens separately.</p>`;
  $('#advanced').onchange=e=>{advanced=e.target.checked;render();};
}
function wireWorkspaces(){document.querySelectorAll('.workspace').forEach(b=>b.addEventListener('click',()=>openView(b.dataset.id,null)));}
function renderViews(){const rows=state.repos;$('#content').innerHTML=`<p class="section-intro">Every repo has a small notes view to demonstrate persistent JSON. You can also register an existing HTML file from a repo. Views stay on this Mac and save data in the helper’s local workspace folder.</p><div class="view-grid">${rows.map(r=>`<article class="view-card"><h3>${escape(r.name)}</h3><p>Local workspace notes</p><button class="workspace" data-id="${r.id}">Open notes view</button>${state.views.filter(v=>v.repo_id===r.id).map(v=>` <button class="registered" data-id="${v.id}">${escape(v.title)}</button>`).join('')}</article>`).join('')}</div><section class="panel"><div class="panel-heading"><h2>Add an HTML view</h2></div><form id="view-form" class="form"><select name="repo_id">${rows.map(r=>`<option value="${r.id}">${escape(r.name)}</option>`).join('')}</select><input name="path" placeholder="Relative path, e.g. reports/dashboard.html" required><input name="title" placeholder="View name" required><button class="primary">Add view</button></form></section><p class="hint">Future views can use <code>RepoHub.getJSON('name')</code> and <code>RepoHub.saveJSON('name', value)</code>. Saves are scoped to the selected repo and check for conflicting edits.</p>`;wireWorkspaces();document.querySelectorAll('.registered').forEach(b=>b.onclick=()=>{const view=state.views.find(v=>v.id===b.dataset.id);openView(view.repo_id,view);});$('#view-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/views',Object.fromEntries(new FormData(e.target)));await load();}catch(err){message(err.message);}};}
function openView(repoId,view){const repo=state.repos.find(r=>r.id===repoId);if(!repo)return;page='views';$('#title').textContent=repo.name;$('#subtitle').textContent=view?.title||'Workspace notes · saved locally as JSON';$('#content').innerHTML='<p><button id="back">← Back to repo views</button></p><iframe id="view-frame" class="view-window" sandbox="allow-scripts allow-forms" title="Repo view"></iframe>';frameScope={repoId};const frame=$('#view-frame');frame.src=view?'/views/'+view.id+'/'+view.path.split('/').map(encodeURIComponent).join('/'):'/notes.html';$('#back').onclick=()=>{frameScope=null;render();};}
window.addEventListener('message',async event=>{const frame=$('#view-frame');if(!frameScope||!frame||event.source!==frame.contentWindow||event.origin!=='null')return;const m=event.data;if(!m||m.channel!=='repohub'||!['get','save'].includes(m.action)||typeof m.name!=='string')return;try{const path='/api/data/'+frameScope.repoId+'/'+encodeURIComponent(m.name);const result=await api(path,m.action==='save'?{value:m.value,revision:m.revision}:undefined);event.source.postMessage({channel:'repohub-result',requestId:m.requestId,result},'*');}catch(e){event.source.postMessage({channel:'repohub-result',requestId:m.requestId,error:e.message},'*');}});
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{frameScope=null;page=b.dataset.page;document.querySelectorAll('nav button').forEach(n=>n.classList.toggle('active',n===b));render();});
$('#refresh').onclick=async()=>{try{await api('/api/scan',{});await load();}catch(e){message(e.message);}};$('#backup').onclick=async()=>{try{await api('/api/backup',{});message('Backup requested.');setTimeout(load,700);}catch(e){message(e.message);}};
(async()=>{try{sessionToken=(await api('/api/session')).token;await load();setInterval(load,30000);}catch(e){message(e.message);}})();
